# Setup
title: Gymnasium Studio Assets Generator
url: https://gymnasium.github.io
baseurl: studio-asset-generator
timezone: America/New_York

# Building

exclude:
  - 'docker-compose.yml'
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'README.md'
  - '.jekyll-cache'


# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  auto_ids:       true
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  input:          GFM
  hard_wrap:      false
  footnote_nr:    1
  show_warnings:  false
